# Generated by Django 3.2.7 on 2021-10-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userimpersonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimpersonation',
            name='expire_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
