# Generated by Django 3.2.7 on 2021-10-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userimpersonation_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acc_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
