apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: nvg-cdp
spec:
  replicas: 3
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: pedro357bm/cdp-auth
          ports:
            - containerPort: 9000
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-auth
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD